require("plugins.neodev")
require("plugins.mason")
require("plugins.lspconfig")
require("plugins.lspsaga")
require("plugins.nvim-cmp")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.nvm-comment")
require("plugins.autopairs")
require("plugins.null-lsp")
require("plugins.treesitter")
--require("plugins.nvim-telescope")

